[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
watchPatterns = [
  "apps/api/email/**",
  "libs/api/**",
  "libs/types/**",
  "nx.json",
  "package.json",
  "tsconfig*.json"
]

[deploy]
healthcheckPath = ""
restartPolicyType = "never"
